### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [haruka-goda/ink_collection#99]
MVPリリースお疲れ様でした。
以下レビュー内容になります。

---

## READMEから課題解決する実装がされているか&動いている
挙動確認を行いまして問題ありませんでした。LGTMです。

## 気になった箇所を挙げるのでご確認ください。
- インクをお気に入りした後に、投稿者がそのインクを削除してしまうと、お気に入りも消えてしまう状態なのかが気になりました。もしそうであるならば、論理削除とかにして残るようにしてあげると良さそうです。
- 万年筆に入っているインクが切れた場合、万年筆の編集まで遷移してインクの入力を空状態で更新する手間がかかるところですが、Pencase表示のところで簡単にから状態に更新できたりすると楽かと感じました。
- 個人的な意見ですが、メーカー表記はカタカナよりも公式に近い形での表記の方が雰囲気が出てよいのではないかと感じました。
- インク・万年筆一覧を見たい際に、空状態で検索しないといけないのも、やや違和感がありました。簡単にワンクリックでそれと分かる動線を用意してあげても良いかと思ます。
- テスト書きましょう。
- オートコンプリートやマルチ検索機能を実装できると、より技術力をアピールできる要素になりそうかと感じました。

---

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。

また書き出したissueをもとに修正完了までのスケジュール・本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by haruka-goda** [comment]
レビューありがとうございました！

・現状はおっしゃる通り、投稿者が削除してしまうとお気に入りからも削除される仕様になっています。ただ、このアプリで投稿が削除されることはあまり無い、と考えております。
（万年筆のインクは使い切ることがそんなにない＆使い切るレベルで好きなインクだったらまた購入の可能性があるので、情報として残しておいた方が利便性が高まるため）
ただ論理削除で残しておく、ということは考えてもいなかったので、どのようにすれば実装できるのかなども踏まえて、考えてみたいと思います。ありがとうございます。

・万年筆とインクの紐付けの実装をどのような形になるかは非常に悩んだのですが、万年筆のインクが切れた場合、万年筆使用者として一番可能性の高いフローとしては「もう一度同じインクを入れる」になります。
インクが空になってそのままの状態にするときには必ず「万年筆を洗う」というアクションがあるため、万年筆からインクを空の状態にするには意図的なものになります。そのため空にするアクションを別で設計する必要はないと判断し、今の形になりました。
ただもっと使いやすくするためにそれを実装する方法なども考えてみたいと思います。

・メーカー表記についても悩んだのですが、アルファベット順ではなく五十音順に並べた方がメーカー名を探しやすい、ということと、万年筆使用者が一番目にしているであろう最大手の万年筆中古販売サイトがカタカナ表記だったため、今の仕様になりました。（「ビスコンティ」「ヴィスコンティ」などの表記揺れに関しても、前述の万年筆サイトにならう形にしました）
ただ、検索でのヒットしやすさも考えると、日本語表記と英語表記を併用する形も良いなとは思っており（その場合、万年筆のインク選択の部分でメーカー名が非常に長ったらしくなるのが悩みどころ）今後考えたいと思います。

・インク一覧、万年筆一覧という形でのリンクボタンは、トップページに用意しています。
ただ、トップページにわざわざ戻ってこずとも、ハンバーガーメニューからのサイドバーや、ヘッダーにある検索バーだけで一覧機能を見ることができる、という検索の使い方を示すために、あえてトップページとマイページの目につくところに置いたタブに、その説明を書きました。

・テストとオートコンプリートの件、承知いたしました。
本リリースは3月1日を目標に実装を進めたいと思います。
よろしくお願いいたします。
